<?php
  define('tmpl_Register', 'Register');
  define('tmpl_Name', 'Name');
  define('tmpl_Required_field', 'Required field');
  define('tmpl_Surname', 'Surname');
  define('tmpl_Date_of_Birth', 'Date of birth');
  define('tmpl_Day', 'Day');
  define('tmpl_Month', 'Month');
  define('tmpl_Year', 'Year');
  define('tmpl_Mobile_Number', 'Mobile Number');
  define('tmpl_Span_Phone', 'Required field, 9 digits');
  define('tmpl_Login', 'Login');
  define('tmpl_Create_Password', 'Create a password');
  define('tmpl_Repeat_Password', 'Repeat password');
  define('tmpl_Choose_Avatar', 'Choose for avatar file .jpg, .jpeg, .gif или .png no more 1 mb');
  define('tmpl_submit_Create_Account', 'Create account');
  define('tmpl_btn_Browse', 'File...');
  define('tmpl_label_Browse', 'Choose avatar');
  define('tmpl_user_exist', 'User with thislogin is already registered, choose another login, please');
  define('tmpl_filefromblacklist', 'Choose for avatar file png, ipg, jpeg, gif no more 1 mb');
  define('tmpl_title_registry_form', 'Registry form');
  define('tmpl_user_profile', 'User account');
  define('tmpl_lang_form', 'Your language is english');
  define('tmpl_Login_in_user_profile', 'Login');
  define('tmpl_user_exist_error', '');
  define('tmpl_psw_is_wrong', 'Password is wrong!');
  define('tmpl_correct_surname', 'Surname is wrong!');
  define('tmpl_cor_u_name', 'Name is wrong!');
  define('tmpl_correct_phonenumb', 'Phone number is wrong!');
  define('tmpl_correct_login', 'Login is wrong!!');
  define('tmpl_is_eq_psw', 'Password and password re are different!!');
  define('tmpl_page_not_found', 'Page not found!');
  define('tmpl_safety_error', 'Safety error. Try again!');