<?php
  define('tmpl_Register', 'Регистрация');
  define('tmpl_Name', 'Имя');
  define('tmpl_Required_field', 'Обязательное поле');
  define('tmpl_Surname', 'Фамилия');
  define('tmpl_Date_of_Birth', 'Дата рождения');
  define('tmpl_Day', 'День');
  define('tmpl_Month', 'Месяц');
  define('tmpl_Year', 'Год');
  define('tmpl_Mobile_Number', 'Мобильный телефон');
  define('tmpl_Span_Phone', 'Поле должно быть заполненным и содержать 9 цифр');
  define('tmpl_Login', 'Укажите логин');
  define('tmpl_Create_Password', 'Придумайте пароль');
  define('tmpl_Repeat_Password', 'Повторите пароль');
  define('tmpl_Choose_Avatar', 'Выберите для аватара файл .jpg, .jpeg, .gif или .png не более 1 mb');
  define('tmpl_submit_Create_Account', 'Зарегистрироваться');
  define('tmpl_btn_Browse', 'Файл...');
  define('tmpl_label_Browse', 'Выберите аватар');
  define('tmpl_user_exist', 'Пользователь с таким логином уже зарегистрирован, выберите другой логин, пожалуйста');
  define('tmpl_filefromblacklist', 'В качестве аватара выберите, пожалуйста, файл png, ipg, jpeg, gif не более 1 mb');
  define('tmpl_title_registry_form', 'Форма регистрации');
  define('tmpl_user_profile', 'Кабинет пользователя');
  define('tmpl_lang_form', 'Язык страницы русский');
  define('tmpl_Login_in_user_profile', 'Логин');
  define('tmpl_user_exist_error', '');
  define('tmpl_psw_is_wrong', 'Пароль либо пуст, либо содержит недопустимые символы!');
  define('tmpl_correct_surname', 'Фамилия либо не заполнена, либо содержит недопустимые символы!');
  define('tmpl_cor_u_name', 'Имя либо не заполнено, либо содержит недопустимые символы!');
  define('tmpl_correct_phonenumb', 'Номер телефона не заполнен, либо содержит недопустимые символы!!');
  define('tmpl_correct_login', 'Логин не заполнен, либо содержит недопустимые символы!!');
  define('tmpl_is_eq_psw', 'Пароли не совпадают!');
  define('tmpl_page_not_found', 'Страница не найдена!');
  define('tmpl_safety_error', 'Ошибка безопасности. Попробуйте еще раз!');